### ISSUE TITLE
Data removed from GI, send valid on the center

### ISSUE THREAD

**Issue by YmaIneo** [fledge-power/fledge-south-iec104#56]
**Describe the bug**
Data manually deleted from GI on RTU is sent valid during GI to center.

**To Reproduce**
1. Initial state I have: [RTU] running <=> [FLEDGEPOWER] running <=> [CENTER] running
2. The state of the GI is correct
3. A data is manually removed from the GI on the RTU
4. The data is set to invalid on the RTU
5. South side GI request : the data is not in the GI (correct action)
6. North side CG request : the center receives the valid data (no correct)

**Expected behavior**
Data manually deleted from GI on RTU is sent invalid during GI to center.

**Comment by aklira** [comment]
Problem fixed
