### ISSUE TITLE
Random IV bit and date when disconnecting rtu

### ISSUE THREAD

**Issue by YmaIneo** [fledge-power/fledge-south-iec104#57]
**Describe the bug**
When disconnecting from the RTU, the data (status point and measured value) is sent immediately to the center. The value of bit IV and the date is set randomly.

**To Reproduce**
1. Initial state I have: [RTU] running <=> [FLEDGEPOWER] running <=> [CENTER] running
2. RTU disconnection
3. The data (status point and measured value) is sent to center (spontaneous)
4. The values of the IV bit and the date are positioned randomly

**Expected behavior**
When disconnecting from the RTU, the data (status point and measured value) is sent immediately to the center. The IV bit must be invalid and the date must be correct.

**Comment by mzillgith** [comment]
This seems to be a problem in the IEC 104 north plugin. The south plugin is sending the quality update correctly but the north plugin ignores it.

**Comment by aklira** [comment]
Problem fixed.
